### ISSUE TITLE
question about training

### ISSUE THREAD

**Issue by SHITIANYU-hue** [anthonyweidai/HierAttn#1]
Dear authors,

thanks for providing this code. when I download the data (https://data.mendeley.com/datasets/zr7vgbcyr2/1) my format is like this, may I know how to integrate into the training framework?

![image](https://user-images.githubusercontent.com/38762389/216191024-45a6e59e-793c-476b-8437-2013ec84a403.png)

![image](https://user-images.githubusercontent.com/38762389/216191099-6c10a113-9dcd-4189-9f6d-6933e1fb7a87.png)

**Comment by anthonyweidai** [comment]
You may need to know the labels for these images from metadata. Sort the images by these labels.

**Comment by anthonyweidai** [comment]
Problem solved.
